apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: mutating-webhook.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: mutating-webhook
        namespace: default
        path: /mutate
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVhRENDQTFDZ0F3SUJBZ0lRZWR4WHk3d3lVckZvakxDc2JlUFB0ekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEkxTURNd05ESXdNamsxT0ZvWERUSTJNRE13TkRJdwpNamsxT0Zvd1NqRVZNQk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRFd0x3WURWUVFERXloemVYTjBaVzA2CmJtOWtaVHB0ZFhSaGRHbHVaeTEzWldKb2IyOXJMbVJsWm1GMWJIUXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBdGowTE1yS1JRMGQ4VkNDd2Z4aytYb1dqSGpabHFXanhsVEpHY05mTQpCYlhHUjdPYjFUT1dzWnZNZFFRMk9oaEFJb3lUSjNjbTVZWFRMa3dxT3JBamJHVGJCRSszbEFvdHpEVHBMVkZoCjMvRXFMNzhmTE9pOFBwM3JnYjlXZVBESmxTaTVta2xRc2p4S1VTTnJKUEZRV0lNKzJ5L3VRWVA1QzVQN2dGdzcKaW55SGVZek5hVGhrbS9iYURDUUw1YmpwQUFQNkJqTlozWkk0TFdYZlFxMHFwWHorOXM0Qld4eEd3RHBmeVMxNgp4KzNHZmpuUzl2WlcwUDdhakg0Y2VMSTg5QjZWSm95V3Z5THo0VEwveGVYbmhSSFFyRVdQcHBid3QxVjNmWFBLCnNIdHpBN3ZBMmYybTc4a00zL3Fpb1pQd3JEdlY5VlRBREZleUFveFMrR0VDMmVNU1dUZXNKMExZS29yVUVYb0UKYXU5UlR6QUcxWkVxMVZ0bm1GYjhKdWRqRk8zamcyTGFEZkxQTy9lMjNFSXlzT1p2VE9hNXE1dFZGZXUvendybApQaktmWlR4QVBoazR1YWpoYWo0bFBRbkpHcTZTK3A3eTBoWEEvQlF0N09QQW9ZcVdQaXAwQk1sV2V6WjA2ajgwCmlBRm1TWWlWM2JsVTRUL2NtSE52YnNFOUFnOXV4VmpsSnNYZTRPODNjVU5PcWVFWnVKTUhhL0xQVVdkZEtrdlAKMXdFK1ZRT2ZiaThMeXVPMTQ4RWFnOTd6VVBJdENPWDBnSjR3M2ZnQmhJMW5BVlhKTVpDMkVPYU5yWkRLZ0ptUApjenlyNld0d1ZYYVBoMWl1ZGVMNWMwLysvNGxHbXdwRFdrT2FMLzlWN2JjcElYQlBJT1NWdUNPNldjNy9YYWhQCkNWc0NBd0VBQWFOL01IMHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUIKTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVK3ZVSHZDdDVqUWtlT2dNTEE5WENXU0IybWJzdwpKd1lEVlIwUkJDQXdIb0ljYlhWMFlYUnBibWN0ZDJWaWFHOXZheTVrWldaaGRXeDBMbk4yWXpBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFKUE1NbnhGWjFkaXpJTzEzVi9Rd05RbitKOXM2Vy9GaGVoSkpucmNzeVl2aXhkQzIKWHF3c0lQazN6RVBXRmdKaEJXL3pIODN1UStNazBTUzQyTE5POVhWVktjVEdqZ29hdDRTTHJPQ2kySEhudXRXLwp2UzJQUFlrYWFxc2VGWW5zSE9Bak5hakt0dkcxd0hIM2hnYUdCSUVWUnRZSDl2S3pPUWNwb1F4OEFHS1k4VHdyClRNRitObmllS05tZ25CYjdhY29ucHFaQ2pGV3ZYZi9YSXpDRlV5SysvZXNqVXlEc1BZZ0FER2VnaVBBeHBoL0oKN0huV1Rob3B2K0IxLy8vT3dYbTFZcDJWcDZyRmxTdjJGVEJqR0dkZ1B4bHRMdlhDaWJ3eG5URzRSZXVBSXRDYgpqc09pTE1vUTR0T1B6a3M3N3lGaHRpakRjc3gzbnB5elMwaEEyUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    failurePolicy: Ignore
    timeoutSeconds: 5
